//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APS_abd.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
  
    
    public partial class adpost
    {
        [Key]
        public int Id { get; set; }
        public Nullable<int> Uid { get; set; }
        [Required]
        public string category { get; set; }
        [Required]
        public string subcategory { get; set; }
        [Required]
        [StringLength(40)]
        public string Title { get; set; }
        public string Description { get; set; }
        [Required]
        [DataType(DataType.Currency)]
        public Nullable<int> Price { get; set; }
        [Required]
        [DataType(DataType.PhoneNumber)]
        public string Phoneno { get; set; }
        [Required]
        public string Location { get; set; }

      
        public Nullable<int> CId { get; set; }
    
        public virtual user user { get; set; }
        public virtual comment_mng comment_mng { get; set; }
    }
}
