//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APS_abd.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class comment_mng
    {
        public comment_mng()
        {
            this.adposts = new HashSet<adpost>();
        }
    
        public int CId { get; set; }
        public Nullable<int> Id { get; set; }
        public string UserName { get; set; }
        [Required]
        public string Comment { get; set; }
    
        public virtual ICollection<adpost> adposts { get; set; }
    }
}
