//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APS_abd.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;
    
    public partial class user
    {
        public user()
        {
            this.adposts = new HashSet<adpost>();
        }

        public int Uid { get; set; }
        [Required]
        [DataType(DataType.EmailAddress)]
        public string Email { get; set; }
          [Required]
     //   [System.Web.Mvc.Remote("CheckUserName", "User"))]
      
        public string UserName { get; set; }
        [Required]
        [DataType(DataType.Password)]
        public string Password { get; set; }
        [Required]
        [DataType(DataType.Password)]
        [System.ComponentModel.DataAnnotations.Compare("Password")]
        public string ConfirmPassword { get; set; }
        public virtual ICollection<adpost> adposts { get; set; }
    }
}
